namespace Shiny.Maui.Controls;

public record Country(string Name, string Code2, string Code3, string DialCode)
{
    public string FlagEmoji { get; } = string.Concat(
        Code2.ToUpperInvariant().Select(c => char.ConvertFromUtf32(c + 0x1F1A5))
    );

    public override string ToString() => Name;
}

public static class CountryData
{
    static List<Country>? all;
    public static IReadOnlyList<Country> All => all ??= BuildList();

    static List<Country> BuildList() =>
    [
        new("Afghanistan", "AF", "AFG", "+93"),
        new("Albania", "AL", "ALB", "+355"),
        new("Algeria", "DZ", "DZA", "+213"),
        new("Andorra", "AD", "AND", "+376"),
        new("Angola", "AO", "AGO", "+244"),
        new("Antigua and Barbuda", "AG", "ATG", "+1-268"),
        new("Argentina", "AR", "ARG", "+54"),
        new("Armenia", "AM", "ARM", "+374"),
        new("Australia", "AU", "AUS", "+61"),
        new("Austria", "AT", "AUT", "+43"),
        new("Azerbaijan", "AZ", "AZE", "+994"),
        new("Bahamas", "BS", "BHS", "+1-242"),
        new("Bahrain", "BH", "BHR", "+973"),
        new("Bangladesh", "BD", "BGD", "+880"),
        new("Barbados", "BB", "BRB", "+1-246"),
        new("Belarus", "BY", "BLR", "+375"),
        new("Belgium", "BE", "BEL", "+32"),
        new("Belize", "BZ", "BLZ", "+501"),
        new("Benin", "BJ", "BEN", "+229"),
        new("Bhutan", "BT", "BTN", "+975"),
        new("Bolivia", "BO", "BOL", "+591"),
        new("Bosnia and Herzegovina", "BA", "BIH", "+387"),
        new("Botswana", "BW", "BWA", "+267"),
        new("Brazil", "BR", "BRA", "+55"),
        new("Brunei", "BN", "BRN", "+673"),
        new("Bulgaria", "BG", "BGR", "+359"),
        new("Burkina Faso", "BF", "BFA", "+226"),
        new("Burundi", "BI", "BDI", "+257"),
        new("Cabo Verde", "CV", "CPV", "+238"),
        new("Cambodia", "KH", "KHM", "+855"),
        new("Cameroon", "CM", "CMR", "+237"),
        new("Canada", "CA", "CAN", "+1"),
        new("Central African Republic", "CF", "CAF", "+236"),
        new("Chad", "TD", "TCD", "+235"),
        new("Chile", "CL", "CHL", "+56"),
        new("China", "CN", "CHN", "+86"),
        new("Colombia", "CO", "COL", "+57"),
        new("Comoros", "KM", "COM", "+269"),
        new("Congo", "CG", "COG", "+242"),
        new("Congo (DRC)", "CD", "COD", "+243"),
        new("Costa Rica", "CR", "CRI", "+506"),
        new("Croatia", "HR", "HRV", "+385"),
        new("Cuba", "CU", "CUB", "+53"),
        new("Cyprus", "CY", "CYP", "+357"),
        new("Czech Republic", "CZ", "CZE", "+420"),
        new("Denmark", "DK", "DNK", "+45"),
        new("Djibouti", "DJ", "DJI", "+253"),
        new("Dominica", "DM", "DMA", "+1-767"),
        new("Dominican Republic", "DO", "DOM", "+1-809"),
        new("Ecuador", "EC", "ECU", "+593"),
        new("Egypt", "EG", "EGY", "+20"),
        new("El Salvador", "SV", "SLV", "+503"),
        new("Equatorial Guinea", "GQ", "GNQ", "+240"),
        new("Eritrea", "ER", "ERI", "+291"),
        new("Estonia", "EE", "EST", "+372"),
        new("Eswatini", "SZ", "SWZ", "+268"),
        new("Ethiopia", "ET", "ETH", "+251"),
        new("Fiji", "FJ", "FJI", "+679"),
        new("Finland", "FI", "FIN", "+358"),
        new("France", "FR", "FRA", "+33"),
        new("Gabon", "GA", "GAB", "+241"),
        new("Gambia", "GM", "GMB", "+220"),
        new("Georgia", "GE", "GEO", "+995"),
        new("Germany", "DE", "DEU", "+49"),
        new("Ghana", "GH", "GHA", "+233"),
        new("Greece", "GR", "GRC", "+30"),
        new("Grenada", "GD", "GRD", "+1-473"),
        new("Guatemala", "GT", "GTM", "+502"),
        new("Guinea", "GN", "GIN", "+224"),
        new("Guinea-Bissau", "GW", "GNB", "+245"),
        new("Guyana", "GY", "GUY", "+592"),
        new("Haiti", "HT", "HTI", "+509"),
        new("Honduras", "HN", "HND", "+504"),
        new("Hungary", "HU", "HUN", "+36"),
        new("Iceland", "IS", "ISL", "+354"),
        new("India", "IN", "IND", "+91"),
        new("Indonesia", "ID", "IDN", "+62"),
        new("Iran", "IR", "IRN", "+98"),
        new("Iraq", "IQ", "IRQ", "+964"),
        new("Ireland", "IE", "IRL", "+353"),
        new("Israel", "IL", "ISR", "+972"),
        new("Italy", "IT", "ITA", "+39"),
        new("Ivory Coast", "CI", "CIV", "+225"),
        new("Jamaica", "JM", "JAM", "+1-876"),
        new("Japan", "JP", "JPN", "+81"),
        new("Jordan", "JO", "JOR", "+962"),
        new("Kazakhstan", "KZ", "KAZ", "+7"),
        new("Kenya", "KE", "KEN", "+254"),
        new("Kiribati", "KI", "KIR", "+686"),
        new("Kuwait", "KW", "KWT", "+965"),
        new("Kyrgyzstan", "KG", "KGZ", "+996"),
        new("Laos", "LA", "LAO", "+856"),
        new("Latvia", "LV", "LVA", "+371"),
        new("Lebanon", "LB", "LBN", "+961"),
        new("Lesotho", "LS", "LSO", "+266"),
        new("Liberia", "LR", "LBR", "+231"),
        new("Libya", "LY", "LBY", "+218"),
        new("Liechtenstein", "LI", "LIE", "+423"),
        new("Lithuania", "LT", "LTU", "+370"),
        new("Luxembourg", "LU", "LUX", "+352"),
        new("Madagascar", "MG", "MDG", "+261"),
        new("Malawi", "MW", "MWI", "+265"),
        new("Malaysia", "MY", "MYS", "+60"),
        new("Maldives", "MV", "MDV", "+960"),
        new("Mali", "ML", "MLI", "+223"),
        new("Malta", "MT", "MLT", "+356"),
        new("Marshall Islands", "MH", "MHL", "+692"),
        new("Mauritania", "MR", "MRT", "+222"),
        new("Mauritius", "MU", "MUS", "+230"),
        new("Mexico", "MX", "MEX", "+52"),
        new("Micronesia", "FM", "FSM", "+691"),
        new("Moldova", "MD", "MDA", "+373"),
        new("Monaco", "MC", "MCO", "+377"),
        new("Mongolia", "MN", "MNG", "+976"),
        new("Montenegro", "ME", "MNE", "+382"),
        new("Morocco", "MA", "MAR", "+212"),
        new("Mozambique", "MZ", "MOZ", "+258"),
        new("Myanmar", "MM", "MMR", "+95"),
        new("Namibia", "NA", "NAM", "+264"),
        new("Nauru", "NR", "NRU", "+674"),
        new("Nepal", "NP", "NPL", "+977"),
        new("Netherlands", "NL", "NLD", "+31"),
        new("New Zealand", "NZ", "NZL", "+64"),
        new("Nicaragua", "NI", "NIC", "+505"),
        new("Niger", "NE", "NER", "+227"),
        new("Nigeria", "NG", "NGA", "+234"),
        new("North Korea", "KP", "PRK", "+850"),
        new("North Macedonia", "MK", "MKD", "+389"),
        new("Norway", "NO", "NOR", "+47"),
        new("Oman", "OM", "OMN", "+968"),
        new("Pakistan", "PK", "PAK", "+92"),
        new("Palau", "PW", "PLW", "+680"),
        new("Palestine", "PS", "PSE", "+970"),
        new("Panama", "PA", "PAN", "+507"),
        new("Papua New Guinea", "PG", "PNG", "+675"),
        new("Paraguay", "PY", "PRY", "+595"),
        new("Peru", "PE", "PER", "+51"),
        new("Philippines", "PH", "PHL", "+63"),
        new("Poland", "PL", "POL", "+48"),
        new("Portugal", "PT", "PRT", "+351"),
        new("Qatar", "QA", "QAT", "+974"),
        new("Romania", "RO", "ROU", "+40"),
        new("Russia", "RU", "RUS", "+7"),
        new("Rwanda", "RW", "RWA", "+250"),
        new("Saint Kitts and Nevis", "KN", "KNA", "+1-869"),
        new("Saint Lucia", "LC", "LCA", "+1-758"),
        new("Saint Vincent and the Grenadines", "VC", "VCT", "+1-784"),
        new("Samoa", "WS", "WSM", "+685"),
        new("San Marino", "SM", "SMR", "+378"),
        new("Sao Tome and Principe", "ST", "STP", "+239"),
        new("Saudi Arabia", "SA", "SAU", "+966"),
        new("Senegal", "SN", "SEN", "+221"),
        new("Serbia", "RS", "SRB", "+381"),
        new("Seychelles", "SC", "SYC", "+248"),
        new("Sierra Leone", "SL", "SLE", "+232"),
        new("Singapore", "SG", "SGP", "+65"),
        new("Slovakia", "SK", "SVK", "+421"),
        new("Slovenia", "SI", "SVN", "+386"),
        new("Solomon Islands", "SB", "SLB", "+677"),
        new("Somalia", "SO", "SOM", "+252"),
        new("South Africa", "ZA", "ZAF", "+27"),
        new("South Korea", "KR", "KOR", "+82"),
        new("South Sudan", "SS", "SSD", "+211"),
        new("Spain", "ES", "ESP", "+34"),
        new("Sri Lanka", "LK", "LKA", "+94"),
        new("Sudan", "SD", "SDN", "+249"),
        new("Suriname", "SR", "SUR", "+597"),
        new("Sweden", "SE", "SWE", "+46"),
        new("Switzerland", "CH", "CHE", "+41"),
        new("Syria", "SY", "SYR", "+963"),
        new("Taiwan", "TW", "TWN", "+886"),
        new("Tajikistan", "TJ", "TJK", "+992"),
        new("Tanzania", "TZ", "TZA", "+255"),
        new("Thailand", "TH", "THA", "+66"),
        new("Timor-Leste", "TL", "TLS", "+670"),
        new("Togo", "TG", "TGO", "+228"),
        new("Tonga", "TO", "TON", "+676"),
        new("Trinidad and Tobago", "TT", "TTO", "+1-868"),
        new("Tunisia", "TN", "TUN", "+216"),
        new("Turkey", "TR", "TUR", "+90"),
        new("Turkmenistan", "TM", "TKM", "+993"),
        new("Tuvalu", "TV", "TUV", "+688"),
        new("Uganda", "UG", "UGA", "+256"),
        new("Ukraine", "UA", "UKR", "+380"),
        new("United Arab Emirates", "AE", "ARE", "+971"),
        new("United Kingdom", "GB", "GBR", "+44"),
        new("United States", "US", "USA", "+1"),
        new("Uruguay", "UY", "URY", "+598"),
        new("Uzbekistan", "UZ", "UZB", "+998"),
        new("Vanuatu", "VU", "VUT", "+678"),
        new("Vatican City", "VA", "VAT", "+379"),
        new("Venezuela", "VE", "VEN", "+58"),
        new("Vietnam", "VN", "VNM", "+84"),
        new("Yemen", "YE", "YEM", "+967"),
        new("Zambia", "ZM", "ZMB", "+260"),
        new("Zimbabwe", "ZW", "ZWE", "+263")
    ];
}
